#!/bin/bash
# USAGE: This just loops through colours and template

######## INIT VARIABLES ########

themes=("BLUEBERRY" "MINT" "LIME" "BANANA" "ORANGE" "STRAWBERRY" "BUBBLEGUM" "GRAPE" "COCOA" "SLATE" "SILVER" "BLACK" "LATTE")

# | tr '[:upper:]' '[:lower:]'

######## SCRIPT ########

for accent_color in ${themes[*]};
do

lessshouting="$(echo $accent_color | tr '[:upper:]' '[:lower:]')"
echo $lessshouting
stylesheet="${lessshouting}.css"

cat << EOF > $stylesheet

/*
* Copyright (c) 2017-2024 Lains
* Copyright (c) 2025 Stella (teamcons on GitHub) and the Ellie_Commons community
*

/* Autogenerated theme for ${accent_color}
Accent colors are defined in the elementary OS stylesheet and like @BLUEBERRY_900
The higher the number the stronger the color.

Normal accent color for, for example BANANANA, is simply
mix(@BANANA_500, @BANANA_700, 0.3);

we cannot simply replace the values of @accent_color_* because css errors and nothing happens
Alas.
*/


window.${accent_color} {
   background-color: @${accent_color}_100;
}

window.${accent_color} undershoot.top {
   background:
       linear-gradient(
           @${accent_color}_100 0%,
           alpha(@${accent_color}_100, 0) 50%
       );
}

window.${accent_color} undershoot.bottom {
   background:
       linear-gradient(
           alpha(@${accent_color}_100, 0) 50%,
           @${accent_color}_100 100%
       );
}

window.${accent_color} overshoot.top {
background: linear-gradient(to top, alpha(@${accent_color}_900, 0) 80%, alpha(@${accent_color}_900, 0.25) 100%); }

window.${accent_color} overshoot.right {
background: linear-gradient(to right, alpha(@${accent_color}_900, 0) 80%, alpha(@${accent_color}_900, 0.25) 100%); }

window.${accent_color} overshoot.bottom {
background: linear-gradient(to bottom, alpha(@${accent_color}_900, 0) 80%, alpha(@${accent_color}_900, 0.25) 100%); }

window.${accent_color} overshoot.left {
background: linear-gradient(to left, alpha(@${accent_color}_900, 0) 80%, alpha(@${accent_color}_900, 0.25) 100%); }

window.${accent_color} textview text selection,
window.${accent_color} editablelabel text selection {
   color: shade(@${accent_color}_100, 1.88);
   background-color: @${accent_color}_900;
}

window.${accent_color} titlebar,
window.${accent_color} titlebar image,
window.${accent_color} actionbar,
window.${accent_color} actionbar image,
window.${accent_color} windowcontrols,
window.${accent_color} windowcontrols image,
window.${accent_color} {
   color: @${accent_color}_900;
}

window.${accent_color} titlebar,
window.${accent_color} textview,
window.${accent_color} textview text,
window.${accent_color} editablelabel.editing text {
   background-color: transparent;
   border-bottom-color: @${accent_color}_100;
   color: shade(@${accent_color}_900, 0.77);
}

/* Fix the emoticon entry having note color background */
window.${accent_color} entry {
   background-color: white;
   color: black;
}

window.${accent_color} editablelabel {
   color: @${accent_color}_900;
}

window.${accent_color} editablelabel:hover,
window.${accent_color} editablelabel:focus {
   border: 1px solid alpha(mix(@${accent_color}_500, @${accent_color}_700, 0.3),0.7);
}

window.${accent_color} editablelabel.editing {
   border: 1px solid mix(@${accent_color}_500, @${accent_color}_700, 0.3);
   box-shadow: inset 0 0 2px 2px mix(@${accent_color}_100, @${accent_color}_500, 0.3);
}

window.${accent_color}:backdrop textview text,
window.${accent_color}:backdrop titlebar,
window.${accent_color}:backdrop editablelabel,
window.${accent_color}:backdrop actionbar,
window.${accent_color}:backdrop actionbar image,
window.${accent_color}:backdrop windowcontrols,
window.${accent_color}:backdrop windowcontrols image {
   color: shade(@${accent_color}_500, 0.77);
}

EOF

done
